[package]
    name = "doop"
    description = "Doop! An open-source Discord guild moderation bot."
    keywords = ["bot", "discord", "serenity"]
    authors = ["Jaxydog"]

    version = "0.1.0"
    edition = "2021"
    publish = false

    repository = "https://github.com/Jaxydog/doop/"
    readme = "docs/readme.md"
    license = "MIT"

[dependencies.chrono]
    version = "0.4"
    features = ["serde"]

[dependencies.clap]
    version = "4.2"
    features = ["derive"]

[dependencies.dotenvy]
    version = "0.15"

[dependencies.flate2]
    version = "1.0"

[dependencies.owo-colors]
    version = "3.5"

[dependencies.rand]
    version = "0.8"

[dependencies.rmp-serde]
    version = "1.1"

[dependencies.serde]
    version = "1.0"
    features = ["derive"]

[dependencies.serenity]
    git = "https://github.com/serenity-rs/serenity"
    branch = "next"
    default-features = false
    features = ["cache", "chrono", "client", "gateway", "model", "rustls_backend", "unstable_discord_api"]

[dependencies.thiserror]
    version = "1.0"

[dependencies.tokio]
    version = "1.27"
    features = ["full"]

[dependencies.toml]
    version = "0.7"
    features = ["preserve_order"]
