edition = "2021"
array_width = 80
attr_fn_like_width = 80
chain_width = 80
comment_width = 100
condense_wildcard_suffixes = true
fn_call_width = 80
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
inline_attribute_width = 80
max_width = 100
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
report_fixme = "Always"
report_todo = "Always"
single_line_if_else_max_width = 80
struct_lit_width = 80
struct_variant_width = 80
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
